# -*- coding: utf-8 -*-
"""different ideology for same place  (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DoBNpouHD_Y9oxdPq-U8wY3o5cvjyngl
"""

from google.colab import drive
drive.mount('/content/drive')

# !pip install gensim sentence-transformers transformers wordcloud rouge
!pip install dash pandas

import os
import pandas as pd
import numpy as np
import re
import dash
from dash import html, dash_table
import pandas as pd

# 处理单个地点的不同思想
def process_location_group(location_data):
    summary_results = []

    # 先对 Category 内的 Response 按 Upvotes 降序排序
    category_sorted = sorted(
        location_data['Category'].unique(),
        key=lambda cat: location_data[location_data['Category'] == cat]['Upvotes'].max(),
        reverse=True
    )

    for category in category_sorted:
        category_data = location_data[location_data['Category'] == category].copy()

        # 先对 Response 按 Upvotes 降序排序
        category_data.sort_values(by='Upvotes', ascending=False, inplace=True)

        for i, (_, row) in enumerate(category_data.iterrows()):
            summary_results.append({
                'Open Location Code': row['Open Location Code'],
                'Category': category,
                'Idea Number': f"idea{i}",
                'Response': row['Response'],
                'Upvotes': row.get('Upvotes', 0),
                'Downvotes': row.get('Downvotes', 0)
            })
    return summary_results

# 主函数，执行整个流程
def main():
    data = pd.read_csv('./drive/MyDrive/apply_data_science/survey_data/survey_responses.csv')
    data.dropna(subset=['Response', 'Category', 'Open Location Code'], inplace=True)

    final_summary_results = []
    for location in data['Open Location Code'].unique():
        location_data = data[data['Open Location Code'] == location]
        location_summaries = process_location_group(location_data)
        final_summary_results.extend(location_summaries)

    final_summary_df = pd.DataFrame(final_summary_results)

    # 调整列顺序
    final_summary_df = final_summary_df[['Open Location Code', 'Category', 'Idea Number', 'Response', 'Upvotes', 'Downvotes']]

    output_path = './drive/MyDrive/apply_data_science/survey_data/conceptual_classified_responses.csv'
    final_summary_df.to_csv(output_path, index=False)
    print(f"分类结果已保存到 {output_path}")

if __name__ == "__main__":
    main()

pd.read_csv('./drive/MyDrive/apply_data_science/survey_data/conceptual_classified_responses.csv')
